//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichierAdmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FichierAdmission()
        {
            this.Lits = new HashSet<Lit>();
        }
    
        public string id { get; set; }
        public string Pat_id { get; set; }
        public string Med_id { get; set; }
        public Nullable<System.DateTime> dateAdmission { get; set; }
        public string parentProche { get; set; }
        public string assurance { get; set; }
        public string conge { get; set; }
        public Nullable<System.DateTime> dateConge { get; set; }
    
        public virtual Medecien Medecien { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lit> Lits { get; set; }
    }
}
