//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lit
    {
        public string id { get; set; }
        public string Fic_id { get; set; }
        public string Cha_id { get; set; }
        public Nullable<bool> Etat { get; set; }
    
        public virtual Chambre Chambre { get; set; }
        public virtual FichierAdmission FichierAdmission { get; set; }
    }
}
